#!/bin/sh

update()
{

  sudo apt update --yes
  sudo apt upgrade --yes
  sudo apt autoremove --yes

  conda update conda --yes
  conda update --all --yes

  brew update
  brew upgrade

  zinit self-update
  zinit update --all

}

# vim: ft=zsh
