#!/bin/sh

update()
{

  conda update conda --yes
  conda update --all --yes

  sudo apt update --yes
  sudo apt upgrade --yes
  sudo apt autoremove --yes

  brew update
  brew upgrade

  zplugin self-update
  zplugin update --all

}

# vim: ft=zsh
